service: verify-users-bank-account-service

package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  lambdaHashingVersion: "20201221"
  environment:
    PAYSTACK_SK: ${env:PAYSTACK_SK}

functions:
  graphql:
    handler: graphQlHandler.server
    environment:
      SLS_DEBUG: true
    events:
      - http:
          path: /graphiql
          method: post
          cors: true
  playground:
    handler: graphQlHandler.playground
    events:
      - http:
          path: /graphiql
          method: get
          cors: true
